windowrule {
    name = brave-no-transparency
    match:class = ^(brave-browser|brave)$

    opacity = 1.0 override 1.0 override
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
windowrule {
    name = steam-client-ws3
    match:class = ^steam$
    match:title = ^Steam$

    workspace = 3
    monitor = HDMI-A-4
}

windowrule {
    name = steam-popups-float
    match:class = ^steam$
    match:title = ^(?!Steam$).*$

    float = true
}

windowrule {
    name = steam-games-special-ws
    match:class = ^steam_app_.*$
    monitor = DP-3
    workspace = special:games
    fullscreen = true
}

windowrule {
    name = bg3-special-ws
    match:class = ^bg3$
    monitor = DP-3
    workspace = special:games
    fullscreen = true
}

# Catch gamescope when used explicitly as a wrapper
windowrule {
    name = gamescope-special-ws
    match:class = ^(gamescope)$
    monitor = DP-3
    workspace = special:games
    fullscreen = true
}
