# Static workspace definitions
workspace = 1, name:browser, persistent:true
workspace = 2, name:terminal, persistent:true
workspace = 3, name:remmina, persistent:true
workspace = 4, name:code, persistent:true

# Assign browser (helium) to workspace 1
windowrule {
    name = browser-ws1
    match:class = ^[Hh]elium
    workspace = 1 silent
}

# Assign terminal (kitty) to workspace 2
windowrule {
    name = terminal-ws2
    #match:class = ^kitty$
    workspace = 2 silent
}

# Assign Remmina to workspace 3 in fullscreen
windowrule {
    name = remmina-ws3
    match:class = ^[Rr]emmina$
    workspace = 3 silent
    fullscreen = true
}

# Assign VSCode to workspace 4
windowrule {
    name = vscode-ws4maximilian
    match:class = ^[Cc]ode
    workspace = 4 silent
}

# Autostart — open each app on its designated workspace at login
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $terminal
#exec-once = [workspace 3 silent] remmina --connect /home/briest/.local/share/remmina/group_rdp_itpc-57djk34_itp2c-57djk34-mpikg-local.remmina
exec-once = [workspace 4 silent] $editor
exec-once = hyprctl dispatch createworkspace special:games