monitor = DP-1, 3840x2160@60, 0x0, 1.5
monitor = DP-2, 3840x2160@60, 2560x0, 1.5

input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
}

# noctalia-shell wird unter Fedora via qs -c aufgerufen
exec-once = qs -c noctalia-shell

bind = $mainMod, SPACE, exec, qs -c noctalia-shell ipc call launcher toggle
bind = $mainMod, L, exec, qs -c noctalia-shell ipc call lockScreen lock
bind = $mainMod ALT, W, exec, qs -c noctalia-shell ipc call wallpaper toggle
bind = $mainMod ALT, T, exec, qs -c noctalia-shell ipc call settings openTab "colorScheme"
bind = CTRLALT, DELETE, exec, qs -c noctalia-shell ipc call sessionMenu toggle
