monitor=HDMI-A-4,1920x1080@60.0,5960x1778,1.0
monitor=DP-2,1920x1080@60.0,1480x1654,1.0
monitor=DP-3,3840x2160@240.08,3400x1294,1.5

input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}