[colors.primary]
background = '#111416'
foreground = '#e2e2e5'
 
[colors.cursor]
text = '#e2e2e5'
cursor = '#c1c7ce' 
 
[colors.vi_mode_cursor]
text = '#111416'
cursor = '#86ceff' 
 
[colors.search.matches]
foreground = '#41484d' 
background = '#cdc0e9' 
 
[colors.search.focused_match]
foreground = '#41484d' 
background = '#86ceff' 
 
[colors.footer_bar]
foreground = '#41484d' 
background = '#e2e2e5' 
 
[colors.hints.start]
foreground = '#41484d' 
background = '#b7c9d8' 
 
[colors.hints.end]
foreground = '#41484d' 
background = '#b7c9d8' 
 
[colors.selection]
text = '#111416'
background = '#86ceff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#86ceff' 
yellow = '#00658f' 
blue = '#86ceff' 
magenta = '#cdc0e9' 
cyan = '#b7c9d8' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 