[colors.primary]
<<<<<<< HEAD
background = '#141316'
foreground = '#e6e1e6'
 
[colors.cursor]
text = '#e6e1e6'
cursor = '#cac4cf' 
 
[colors.vi_mode_cursor]
text = '#141316'
cursor = '#cfbdff' 
 
[colors.search.matches]
foreground = '#49454e' 
background = '#efb8c8' 
 
[colors.search.focused_match]
foreground = '#49454e' 
background = '#cfbdff' 
 
[colors.footer_bar]
foreground = '#49454e' 
background = '#e6e1e6' 
 
[colors.hints.start]
foreground = '#49454e' 
background = '#cbc3dc' 
 
[colors.hints.end]
foreground = '#49454e' 
background = '#cbc3dc' 
 
[colors.selection]
text = '#141316'
background = '#cfbdff'
=======
background = '#171213'
foreground = '#ece0e1'
 
[colors.cursor]
text = '#ece0e1'
cursor = '#d6c2c5' 
 
[colors.vi_mode_cursor]
text = '#171213'
cursor = '#ffb1c4' 
 
[colors.search.matches]
foreground = '#514346' 
background = '#edbd92' 
 
[colors.search.focused_match]
foreground = '#514346' 
background = '#ffb1c4' 
 
[colors.footer_bar]
foreground = '#514346' 
background = '#ece0e1' 
 
[colors.hints.start]
foreground = '#514346' 
background = '#e3bdc5' 
 
[colors.hints.end]
foreground = '#514346' 
background = '#e3bdc5' 
 
[colors.selection]
text = '#171213'
background = '#ffb1c4'
>>>>>>> a0c63df (ganz viel bastelei)
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
<<<<<<< HEAD
green = '#cfbdff' 
yellow = '#6650a4' 
blue = '#cfbdff' 
magenta = '#efb8c8' 
cyan = '#cbc3dc' 
=======
green = '#ffb1c4' 
yellow = '#99405c' 
blue = '#ffb1c4' 
magenta = '#edbd92' 
cyan = '#e3bdc5' 
>>>>>>> a0c63df (ganz viel bastelei)
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 