[colors.primary]
background = '#171214'
foreground = '#ebe0e2'
 
[colors.cursor]
text = '#ebe0e2'
cursor = '#d4c2c7' 
 
[colors.vi_mode_cursor]
text = '#171214'
cursor = '#ffb0d0' 
 
[colors.search.matches]
foreground = '#504348' 
background = '#f1bb97' 
 
[colors.search.focused_match]
foreground = '#504348' 
background = '#ffb0d0' 
 
[colors.footer_bar]
foreground = '#504348' 
background = '#ebe0e2' 
 
[colors.hints.start]
foreground = '#504348' 
background = '#e1bdc9' 
 
[colors.hints.end]
foreground = '#504348' 
background = '#e1bdc9' 
 
[colors.selection]
text = '#171214'
background = '#ffb0d0'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb0d0' 
yellow = '#96416a' 
blue = '#ffb0d0' 
magenta = '#f1bb97' 
cyan = '#e1bdc9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 