color0 #171214
color1 #ffb4ab
color2 #ffb0d0
color3 #e1bdc9
color4 #f1bb97
color5 #ffb0d0
color6 #e1bdc9
color7 #ebe0e2
color8 #9d8c91
color9 #ffb4ab
color10 #ffb0d0
color11 #e1bdc9
color12 #f1bb97
color13 #ffb0d0
color14 #e1bdc9
color15 #ebe0e2

cursor                #ebe0e2
cursor_text_color     #171214
background            #171214
foreground            #ebe0e2
selection_foreground  #d4c2c7
selection_background  #504348
active_border_color   #ffb0d0
inactive_border_color #504348
url_color             #ffb0d0

active_tab_foreground   #5c113a
active_tab_background   #ffb0d0
inactive_tab_foreground #d4c2c7
inactive_tab_background #504348
cursor_trail_color      #d4c2c7
